GET http://localhost:3000/sickLeave/ HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBha2RvZGljb250b2hAZ21haWwuY29tIiwiaWQiOiI2MWExYTliYmZmNWE3NzFjNzAyNGM1ZWYiLCJpYXQiOjE2Mzc5ODUxMzR9.BfI0L3HkBP6-28hYf3ybmOimrzwR2K-AkofR_wyryWw
Content-Type: application/json

###

GET http://localhost:3000/sickLeave/617a10c6846909fe3363c55a HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBha2RvZGljb250b2hAZ21haWwuY29tIiwiaWQiOiI2MTVkNTFjYmU3OTg3MTk2ZGUzZGE3YWQiLCJpYXQiOjE2MzU0NzU5NjAsImV4cCI6MTYzNTU2MjM2MH0.yDjYe4vn2vkG7dZv7ziQK890xn3QkPnqHIMpGzOSYqE
Content-Type: application/json


###

PATCH http://localhost:3000/sickLeave/accept/61a74a10db6053e35b210c5e HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBha2RvZGljb250b2hAZ21haWwuY29tIiwiaWQiOiI2MWExYTliYmZmNWE3NzFjNzAyNGM1ZWYiLCJpYXQiOjE2MzgzNTMxMTl9._S5txXuy9AhiXxlP1uy1Kb1J3XO3oX02Y-d6KSRBJ3Q
Content-Type: application/json

{
    "accept": "accepted"
}

###

DELETE http://localhost:3000/sickLeave/6178cedc6e9272918c46988b HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBha2RvZGljb250b2hAZ21haWwuY29tIiwiaWQiOiI2MTVkNTFjYmU3OTg3MTk2ZGUzZGE3YWQiLCJpYXQiOjE2MzUzMDA3MTksImV4cCI6MTYzNTM4NzExOX0.tzk_IFI4ERZmTW0K0y3yuw6cJfqwWyp7pzMYW5_gyt8
Content-Type: application/json

###